import { Inter } from "next/font/google";
import { CiUser } from "react-icons/ci";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=" bg-white">
      <body className={`${inter.className} bg-white text-black`}>
        <header className=" border-b-2 border-color-blue flex max-w w-full justify-between p-3 bg-color-gray">
          <img src="../../images/logo-hackathan.svg" />

          <nav className=" flex items-center">
            <ul className=" flex">
              <li className="">
                <a
                  className="text-xl h-full transition-all ease-in-out duration-100 hover:text-color-orange"
                  href="/contribuicao"
                >
                  Faça uma contribuição
                </a>
              </li>
              <li className=" mx-6">
                <a
                  className="text-xl h-full transition-all ease-in-out duration-100 hover:text-color-orange"
                  href="https://www.gov.br/arquivonacional/pt-br"
                >
                  Conheça o AN
                </a>
              </li>
              <li>
                <a
                  className="text-xl h-full transition-all ease-in-out duration-100 hover:text-color-orange"
                  href="/criaConta"
                >
                  Registre-se
                </a>
              </li>
            </ul>
          </nav>

          <a href="/login" className="hover:text-6xl">
            <CiUser className=" text-4xl transition-all ease-in-out duration-100 text-color-orange hover:text-color-dark-orange" />
          </a>
        </header>
        {children}
        <footer className=" flex justify-center bg-color-gray w-full py-5">
          <a href="https://www.gov.br/arquivonacional/pt-br" target="_blank">
            <img src="../../images/an-logo.png" />
          </a>
        </footer>
      </body>
    </html>
  );
}
